# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhydra.proto\x12\x07grpcapi\",\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"A\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"!\n\x11\x43lientTaskRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"6\n\x12\x43lientTaskResponse\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\"5\n\x10HeartbeatRequest\x12\x10\n\x08workerId\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\")\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"\x8c\x01\n\x17UpdateTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.grpcapi.TaskStatus\x12\x12\n\nstarted_at\x18\x03 \x01(\x03\x12\x14\n\x0c\x63ompleted_at\x18\x04 \x01(\x03\x12\x11\n\tfailed_at\x18\x05 \x01(\x03\"+\n\x18UpdateTaskStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*?\n\nTaskStatus\x12\n\n\x06QUEUED\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x0c\n\x08\x43OMPLETE\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32L\n\rWorkerService\x12;\n\nSubmitTask\x12\x14.grpcapi.TaskRequest\x1a\x15.grpcapi.TaskResponse\"\x00\x32\x82\x02\n\x12\x43oordinatorService\x12G\n\nSubmitTask\x12\x1a.grpcapi.ClientTaskRequest\x1a\x1b.grpcapi.ClientTaskResponse\"\x00\x12H\n\rSendHeartbeat\x12\x19.grpcapi.HeartbeatRequest\x1a\x1a.grpcapi.HeartbeatResponse\"\x00\x12Y\n\x10UpdateTaskStatus\x12 .grpcapi.UpdateTaskStatusRequest\x1a!.grpcapi.UpdateTaskStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSTATUS']._serialized_start=514
  _globals['_TASKSTATUS']._serialized_end=577
  _globals['_TASKREQUEST']._serialized_start=24
  _globals['_TASKREQUEST']._serialized_end=68
  _globals['_TASKRESPONSE']._serialized_start=70
  _globals['_TASKRESPONSE']._serialized_end=135
  _globals['_CLIENTTASKREQUEST']._serialized_start=137
  _globals['_CLIENTTASKREQUEST']._serialized_end=170
  _globals['_CLIENTTASKRESPONSE']._serialized_start=172
  _globals['_CLIENTTASKRESPONSE']._serialized_end=226
  _globals['_HEARTBEATREQUEST']._serialized_start=228
  _globals['_HEARTBEATREQUEST']._serialized_end=281
  _globals['_HEARTBEATRESPONSE']._serialized_start=283
  _globals['_HEARTBEATRESPONSE']._serialized_end=324
  _globals['_UPDATETASKSTATUSREQUEST']._serialized_start=327
  _globals['_UPDATETASKSTATUSREQUEST']._serialized_end=467
  _globals['_UPDATETASKSTATUSRESPONSE']._serialized_start=469
  _globals['_UPDATETASKSTATUSRESPONSE']._serialized_end=512
  _globals['_WORKERSERVICE']._serialized_start=579
  _globals['_WORKERSERVICE']._serialized_end=655
  _globals['_COORDINATORSERVICE']._serialized_start=658
  _globals['_COORDINATORSERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
